spring:
  profiles:
    active: dev

mybatis:
  #typeAliasesPackage: com.jm.orm.springboot.mybatis.entity
  mapperLocations: classpath:mapper/*.xml

server:
  port: 8082
---

#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/spark_project
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource