
spring:
  datasource:
    druid:
      driver-class-name: org.postgresql.Driver
      username: dm
      password: hzmcdm
      url: jdbc:postgresql://192.168.239.1:5432/dm?useUnicode=true&characterEncoding=utf-8
      type: com.alibaba.druid.pool.DruidDataSource
    type: com.alibaba.druid.pool.DruidDataSource

